# Server
server:
    port: 80
# H2 Web Console (H2ConsoleProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartfarm22
    name:
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
    hibernate:
      ddl-auto: update